Repository CBNU-CMI/React-Back-end, pull requests merged in 2020-10, with the labels that each got.

#5 [#4] feat: major, common api
  app.js
  db/notice.js
  routes/notice.js
Labels: back-end, feature

#7 월간 스케쥴 api 작성
  app.js
  db/schedule.js
  routes/schedule.js
Labels: back-end

#10 [#9] fix: offset
  routes/notice.js
Labels: back-end, bug
